export type DailyWord = {
  word: string;
  pos: string;
  level: "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
  translation: string;
  example: string;
  exampleTranslation: string;
};

/**
 * Pool of French "word of the day" entries.
 * Cycled deterministically by date (see lib/daily.ts).
 * Curated for variety across CEFR levels and parts of speech.
 */
export const DAILY_WORDS: DailyWord[] = [
  { word: "flâner", pos: "verb", level: "B2", translation: "to stroll, wander aimlessly", example: "J’aime flâner dans les rues de Paris le dimanche.", exampleTranslation: "I love wandering through the streets of Paris on Sundays." },
  { word: "dépaysement", pos: "noun (m.)", level: "C1", translation: "the feeling of being in a foreign place; a change of scenery", example: "Ce voyage au Japon m’a procuré un véritable dépaysement.", exampleTranslation: "This trip to Japan gave me a true change of scenery." },
  { word: "chuchoter", pos: "verb", level: "B1", translation: "to whisper", example: "Elle m’a chuchoté un secret à l’oreille.", exampleTranslation: "She whispered a secret in my ear." },
  { word: "épanouir (s’)", pos: "verb (refl.)", level: "B2", translation: "to blossom, to thrive", example: "Il s’épanouit dans son nouveau métier.", exampleTranslation: "He’s thriving in his new job." },
  { word: "gourmand", pos: "adj.", level: "A2", translation: "fond of good food; greedy (in a charming way)", example: "Mon petit frère est très gourmand.", exampleTranslation: "My little brother loves sweets and food." },
  { word: "ailleurs", pos: "adv.", level: "B1", translation: "elsewhere", example: "Cherchons ailleurs, ce magasin est fermé.", exampleTranslation: "Let’s look elsewhere, this shop is closed." },
  { word: "ravi", pos: "adj.", level: "A2", translation: "delighted", example: "Je suis ravi de te revoir.", exampleTranslation: "I’m delighted to see you again." },
  { word: "tellement", pos: "adv.", level: "A2", translation: "so much / so", example: "Il fait tellement chaud aujourd’hui.", exampleTranslation: "It’s so hot today." },
  { word: "quotidien", pos: "adj./noun", level: "B1", translation: "daily; daily life", example: "Le café fait partie de mon quotidien.", exampleTranslation: "Coffee is part of my daily routine." },
  { word: "soulager", pos: "verb", level: "B1", translation: "to relieve", example: "Cette nouvelle m’a soulagé.", exampleTranslation: "This news was a relief to me." },
  { word: "tisser", pos: "verb", level: "B2", translation: "to weave (also: to build, e.g., bonds)", example: "Ils ont tissé des liens forts au fil des années.", exampleTranslation: "They built strong bonds over the years." },
  { word: "ébloui", pos: "adj.", level: "B2", translation: "dazzled", example: "J’étais ébloui par la beauté du paysage.", exampleTranslation: "I was dazzled by the beauty of the landscape." },
  { word: "lendemain", pos: "noun (m.)", level: "A2", translation: "the next day", example: "Le lendemain, il pleuvait encore.", exampleTranslation: "The next day, it was still raining." },
  { word: "songer", pos: "verb", level: "B2", translation: "to think (about), to consider", example: "Je songe à déménager en Bretagne.", exampleTranslation: "I’m thinking of moving to Brittany." },
  { word: "veiller", pos: "verb", level: "B1", translation: "to stay up; to watch over", example: "Veille à fermer la porte à clé.", exampleTranslation: "Make sure to lock the door." },
  { word: "soigner", pos: "verb", level: "A2", translation: "to take care of, to treat", example: "Le médecin a soigné ma grippe.", exampleTranslation: "The doctor treated my flu." },
  { word: "égarer", pos: "verb", level: "B2", translation: "to misplace; to lead astray", example: "J’ai égaré mes clés ce matin.", exampleTranslation: "I misplaced my keys this morning." },
  { word: "douillet", pos: "adj.", level: "B2", translation: "cozy, snug", example: "Mon canapé est tout douillet en hiver.", exampleTranslation: "My couch is so cozy in winter." },
  { word: "bavarder", pos: "verb", level: "A2", translation: "to chat", example: "Nous avons bavardé pendant des heures.", exampleTranslation: "We chatted for hours." },
  { word: "épuiser", pos: "verb", level: "B1", translation: "to exhaust, to use up", example: "Ce travail m’a complètement épuisé.", exampleTranslation: "This work has completely exhausted me." },
  { word: "rouspéter", pos: "verb", level: "C1", translation: "to grumble, complain", example: "Mon voisin rouspète tout le temps.", exampleTranslation: "My neighbor grumbles all the time." },
  { word: "soudain", pos: "adv./adj.", level: "A2", translation: "suddenly; sudden", example: "Soudain, le ciel s’est obscurci.", exampleTranslation: "Suddenly, the sky darkened." },
  { word: "deviner", pos: "verb", level: "A2", translation: "to guess", example: "Devine qui est venu hier !", exampleTranslation: "Guess who came over yesterday!" },
  { word: "épice", pos: "noun (f.)", level: "A2", translation: "spice", example: "J’adore les épices indiennes.", exampleTranslation: "I love Indian spices." },
  { word: "rassurer", pos: "verb", level: "B1", translation: "to reassure", example: "Sa voix m’a rassuré.", exampleTranslation: "Her voice reassured me." },
  { word: "embêter", pos: "verb", level: "A2", translation: "to bother, to annoy", example: "Arrête de m’embêter !", exampleTranslation: "Stop bothering me!" },
  { word: "puiser", pos: "verb", level: "B2", translation: "to draw (from), to tap into", example: "Il puise son inspiration dans la nature.", exampleTranslation: "He draws his inspiration from nature." },
  { word: "rusé", pos: "adj.", level: "B1", translation: "cunning, sly", example: "Le renard est un animal rusé.", exampleTranslation: "The fox is a cunning animal." },
  { word: "fier", pos: "adj.", level: "A2", translation: "proud", example: "Je suis fier de toi.", exampleTranslation: "I’m proud of you." },
  { word: "tiède", pos: "adj.", level: "A2", translation: "lukewarm", example: "Mon café est devenu tiède.", exampleTranslation: "My coffee has gone lukewarm." },
  { word: "envergure", pos: "noun (f.)", level: "C1", translation: "scale, scope, stature", example: "C’est un projet d’une grande envergure.", exampleTranslation: "It’s a project of great scope." },
  { word: "jadis", pos: "adv.", level: "C1", translation: "in days gone by, formerly", example: "Jadis, ce château abritait des rois.", exampleTranslation: "Long ago, this castle housed kings." },
  { word: "amer", pos: "adj.", level: "B1", translation: "bitter", example: "Ce café est trop amer.", exampleTranslation: "This coffee is too bitter." },
  { word: "frémir", pos: "verb", level: "B2", translation: "to shiver; to simmer", example: "Faites frémir l’eau, sans la faire bouillir.", exampleTranslation: "Bring the water to a simmer, but don’t boil it." },
  { word: "agacer", pos: "verb", level: "B1", translation: "to annoy, to irritate", example: "Ce bruit m’agace.", exampleTranslation: "That noise is annoying me." },
  { word: "songeur", pos: "adj.", level: "C1", translation: "thoughtful, pensive", example: "Elle est restée songeuse un long moment.", exampleTranslation: "She remained pensive for a long while." },
  { word: "patrimoine", pos: "noun (m.)", level: "B2", translation: "heritage, patrimony", example: "Ce monument fait partie du patrimoine national.", exampleTranslation: "This monument is part of the national heritage." },
  { word: "trottoir", pos: "noun (m.)", level: "A2", translation: "sidewalk", example: "Marche sur le trottoir, c’est plus sûr.", exampleTranslation: "Walk on the sidewalk, it’s safer." },
  { word: "convaincre", pos: "verb", level: "B2", translation: "to convince", example: "Tu m’as convaincu.", exampleTranslation: "You’ve convinced me." },
  { word: "lever", pos: "verb/noun", level: "A1", translation: "to raise; sunrise (le lever)", example: "Le lever du soleil était magnifique.", exampleTranslation: "The sunrise was magnificent." },
  { word: "marrant", pos: "adj.", level: "B1", translation: "funny (colloquial)", example: "Ce film est vraiment marrant.", exampleTranslation: "This movie is really funny." },
  { word: "frangin", pos: "noun (m.)", level: "B2", translation: "bro, brother (slang)", example: "Salut frangin, ça va ?", exampleTranslation: "Hey bro, how’s it going?" },
  { word: "potable", pos: "adj.", level: "B1", translation: "drinkable; (fig.) acceptable", example: "L’eau du robinet est potable ici.", exampleTranslation: "The tap water is drinkable here." },
  { word: "saugrenu", pos: "adj.", level: "C1", translation: "absurd, preposterous", example: "Quelle idée saugrenue !", exampleTranslation: "What a preposterous idea!" },
  { word: "moelleux", pos: "adj.", level: "B1", translation: "soft, fluffy (food/fabric)", example: "Ce gâteau est très moelleux.", exampleTranslation: "This cake is very soft." },
  { word: "frileux", pos: "adj.", level: "B2", translation: "sensitive to cold; (fig.) cautious", example: "Je suis frileux, je porte toujours un pull.", exampleTranslation: "I’m sensitive to cold; I always wear a sweater." },
  { word: "drôle", pos: "adj.", level: "A1", translation: "funny; (before noun) strange", example: "C’est une drôle d’histoire.", exampleTranslation: "It’s a strange story." },
  { word: "ressentir", pos: "verb", level: "B1", translation: "to feel (an emotion)", example: "Je ressens beaucoup de gratitude.", exampleTranslation: "I feel a lot of gratitude." },
  { word: "bricoler", pos: "verb", level: "B1", translation: "to tinker, do DIY", example: "Mon père aime bricoler le week-end.", exampleTranslation: "My dad loves doing DIY on weekends." },
  { word: "rêverie", pos: "noun (f.)", level: "C1", translation: "daydream, reverie", example: "Il est plongé dans ses rêveries.", exampleTranslation: "He’s lost in his daydreams." },
  { word: "minutieux", pos: "adj.", level: "B2", translation: "meticulous", example: "Un travail minutieux exige du temps.", exampleTranslation: "Meticulous work requires time." },
  { word: "louche", pos: "adj./noun", level: "B1", translation: "shady, suspicious; ladle (noun)", example: "Ce type a l’air louche.", exampleTranslation: "That guy looks shady." },
  { word: "frôler", pos: "verb", level: "B2", translation: "to brush against; to come close to", example: "Il a frôlé la victoire.", exampleTranslation: "He came close to winning." },
  { word: "ronfler", pos: "verb", level: "B1", translation: "to snore", example: "Mon mari ronfle la nuit.", exampleTranslation: "My husband snores at night." },
  { word: "potin", pos: "noun (m.)", level: "C1", translation: "gossip, tittle-tattle", example: "Elle adore les potins.", exampleTranslation: "She loves gossip." },
  { word: "guetter", pos: "verb", level: "B2", translation: "to watch out for, to look out for", example: "Je guette son retour à la fenêtre.", exampleTranslation: "I’m watching out for his return at the window." },
  { word: "humer", pos: "verb", level: "C1", translation: "to inhale, to breathe in (a smell)", example: "Elle humait le parfum des roses.", exampleTranslation: "She was breathing in the scent of roses." },
  { word: "vaillant", pos: "adj.", level: "C1", translation: "brave, valiant", example: "Un cœur vaillant ne recule jamais.", exampleTranslation: "A brave heart never backs down." },
  { word: "se débrouiller", pos: "verb (refl.)", level: "B1", translation: "to manage, to get by", example: "Ne t’inquiète pas, je me débrouillerai.", exampleTranslation: "Don’t worry, I’ll manage." },
  { word: "bruyant", pos: "adj.", level: "A2", translation: "noisy", example: "Ce café est trop bruyant pour travailler.", exampleTranslation: "This cafe is too noisy for working." },
  { word: "chaleureux", pos: "adj.", level: "B1", translation: "warm (welcome, person)", example: "Un accueil chaleureux nous attendait.", exampleTranslation: "A warm welcome was waiting for us." },
  { word: "fougueux", pos: "adj.", level: "C1", translation: "fiery, spirited", example: "Un cheval fougueux n’est pas facile à monter.", exampleTranslation: "A spirited horse is not easy to ride." },
  { word: "couler", pos: "verb", level: "A2", translation: "to flow; to sink", example: "La rivière coule lentement.", exampleTranslation: "The river flows slowly." },
  { word: "espiègle", pos: "adj.", level: "C1", translation: "mischievous, playful", example: "Cet enfant est espiègle mais adorable.", exampleTranslation: "This child is mischievous but adorable." },
  { word: "essoufflé", pos: "adj.", level: "B2", translation: "out of breath", example: "J’arrive essoufflé après les escaliers.", exampleTranslation: "I arrive out of breath after the stairs." },
  { word: "rancune", pos: "noun (f.)", level: "B2", translation: "grudge", example: "Sans rancune !", exampleTranslation: "No hard feelings!" },
  { word: "ailes", pos: "noun (f. pl.)", level: "A2", translation: "wings", example: "L’oiseau battait des ailes.", exampleTranslation: "The bird was flapping its wings." },
  { word: "ourlet", pos: "noun (m.)", level: "C1", translation: "hem", example: "J’ai fait l’ourlet de mon pantalon.", exampleTranslation: "I hemmed my trousers." },
  { word: "veille", pos: "noun (f.)", level: "A2", translation: "the day before; vigil", example: "La veille de Noël est magique.", exampleTranslation: "Christmas Eve is magical." },
  { word: "souffle", pos: "noun (m.)", level: "B1", translation: "breath; gust", example: "Le souffle du vent rafraîchit l’air.", exampleTranslation: "The gust of wind freshens the air." },
  { word: "se vanter", pos: "verb (refl.)", level: "B2", translation: "to brag, to boast", example: "Il se vante toujours de ses voyages.", exampleTranslation: "He always brags about his travels." },
  { word: "ricaner", pos: "verb", level: "B2", translation: "to snicker, sneer", example: "Arrête de ricaner, ce n’est pas drôle.", exampleTranslation: "Stop snickering, it’s not funny." },
  { word: "tendresse", pos: "noun (f.)", level: "B1", translation: "tenderness, affection", example: "Elle parle de ses enfants avec tendresse.", exampleTranslation: "She speaks of her children with tenderness." },
  { word: "bouder", pos: "verb", level: "B2", translation: "to sulk", example: "Il boude depuis ce matin.", exampleTranslation: "He’s been sulking since this morning." },
  { word: "couvrir", pos: "verb", level: "A2", translation: "to cover", example: "Couvre-toi bien, il fait froid.", exampleTranslation: "Bundle up, it’s cold." },
  { word: "remue-ménage", pos: "noun (m.)", level: "C1", translation: "commotion, hustle and bustle", example: "Quel remue-ménage dans la cuisine !", exampleTranslation: "What a commotion in the kitchen!" },
  { word: "fadaise", pos: "noun (f.)", level: "C2", translation: "nonsense, twaddle", example: "Ne raconte pas de fadaises.", exampleTranslation: "Don’t talk nonsense." },
  { word: "ronchon", pos: "adj./noun", level: "B2", translation: "grouchy; grumbler", example: "Mon oncle est un vieux ronchon.", exampleTranslation: "My uncle is an old grouch." },
  { word: "siffler", pos: "verb", level: "A2", translation: "to whistle", example: "Il siffle toujours la même chanson.", exampleTranslation: "He always whistles the same song." },
  { word: "ébranler", pos: "verb", level: "C1", translation: "to shake, to unsettle", example: "Cette nouvelle l’a ébranlé.", exampleTranslation: "This news shook him." },
  { word: "câlin", pos: "noun (m.)/adj.", level: "A2", translation: "hug, cuddle; affectionate", example: "Viens, fais-moi un câlin.", exampleTranslation: "Come, give me a hug." },
  { word: "péripétie", pos: "noun (f.)", level: "C1", translation: "twist, adventure (in a story)", example: "Le voyage a connu mille péripéties.", exampleTranslation: "The trip went through countless twists." },
  { word: "savourer", pos: "verb", level: "B2", translation: "to savor, to relish", example: "Savoure chaque instant.", exampleTranslation: "Savor every moment." },

  // --- Expansion pool ------------------------------------------------------
  { word: "matinée", pos: "noun (f.)", level: "A2", translation: "morning (duration)", example: "J’ai passé toute la matinée à lire.", exampleTranslation: "I spent the whole morning reading." },
  { word: "bouquin", pos: "noun (m.)", level: "B1", translation: "book (informal)", example: "J’ai trouvé un super bouquin à la brocante.", exampleTranslation: "I found a great book at the flea market." },
  { word: "boulot", pos: "noun (m.)", level: "B1", translation: "job, work (informal)", example: "J’ai trop de boulot cette semaine.", exampleTranslation: "I’ve got too much work this week." },
  { word: "rigoler", pos: "verb", level: "B1", translation: "to laugh, to joke around", example: "On a bien rigolé hier soir.", exampleTranslation: "We had a good laugh last night." },
  { word: "se balader", pos: "verb (refl.)", level: "A2", translation: "to wander, to take a walk", example: "On va se balader au bord de la Seine ?", exampleTranslation: "Shall we take a walk along the Seine?" },
  { word: "doudou", pos: "noun (m.)", level: "A2", translation: "stuffed animal, comfort toy", example: "L’enfant ne se sépare jamais de son doudou.", exampleTranslation: "The child never parts with his stuffed toy." },
  { word: "klaxonner", pos: "verb", level: "B1", translation: "to honk", example: "Le chauffeur klaxonnait sans arrêt.", exampleTranslation: "The driver kept honking nonstop." },
  { word: "moche", pos: "adj.", level: "A2", translation: "ugly, lame", example: "Cette veste est vraiment moche.", exampleTranslation: "This jacket is really ugly." },
  { word: "louper", pos: "verb", level: "B1", translation: "to miss, to mess up (informal)", example: "J’ai loupé mon train de cinq minutes.", exampleTranslation: "I missed my train by five minutes." },
  { word: "tarder", pos: "verb", level: "B2", translation: "to be slow (to do something), to delay", example: "Il ne va pas tarder à arriver.", exampleTranslation: "He won’t be long now." },
  { word: "naguère", pos: "adv.", level: "C1", translation: "not long ago, formerly", example: "Naguère, ce village était plein de vie.", exampleTranslation: "Not so long ago, this village was full of life." },
  { word: "exiger", pos: "verb", level: "B2", translation: "to demand, to require", example: "Ce poste exige de la rigueur.", exampleTranslation: "This position demands rigor." },
  { word: "averse", pos: "noun (f.)", level: "B1", translation: "a sudden downpour", example: "Une averse nous a surpris en chemin.", exampleTranslation: "A sudden downpour caught us on the way." },
  { word: "froussard", pos: "adj./noun", level: "C1", translation: "scaredy-cat, chicken (slang)", example: "Ne sois pas si froussard, c’est qu’un orage.", exampleTranslation: "Don’t be such a scaredy-cat, it’s just a storm." },
  { word: "ahurissant", pos: "adj.", level: "C1", translation: "astounding, mind-boggling", example: "Le prix de ce loyer est ahurissant.", exampleTranslation: "The price of this rent is astounding." },
  { word: "cligner", pos: "verb", level: "B2", translation: "to blink, to wink", example: "Il cligne des yeux à cause de la lumière.", exampleTranslation: "He’s blinking because of the light." },
  { word: "ronchonner", pos: "verb", level: "B2", translation: "to grumble", example: "Mon père ronchonne dès qu’il pleut.", exampleTranslation: "My dad grumbles the minute it rains." },
  { word: "rigolo", pos: "adj.", level: "B1", translation: "funny, amusing (colloquial)", example: "Ton chien est trop rigolo.", exampleTranslation: "Your dog is so funny." },
  { word: "épater", pos: "verb", level: "B2", translation: "to impress, to amaze", example: "Tu vas les épater avec ton gâteau.", exampleTranslation: "You’re going to amaze them with your cake." },
  { word: "frigo", pos: "noun (m.)", level: "A2", translation: "fridge (informal)", example: "Le frigo est vide, il faut faire les courses.", exampleTranslation: "The fridge is empty, we need to go shopping." },
  { word: "embarras", pos: "noun (m.)", level: "B2", translation: "embarrassment; predicament", example: "Tu m’as tiré d’un sacré embarras.", exampleTranslation: "You got me out of quite a predicament." },
  { word: "se taire", pos: "verb (refl.)", level: "B1", translation: "to be quiet, to fall silent", example: "Tais-toi, j’essaie d’écouter.", exampleTranslation: "Be quiet, I’m trying to listen." },
  { word: "gâcher", pos: "verb", level: "B1", translation: "to spoil, to waste", example: "Ne gâche pas la surprise.", exampleTranslation: "Don’t spoil the surprise." },
  { word: "se méfier", pos: "verb (refl.)", level: "B1", translation: "to be wary of", example: "Méfie-toi des arnaques en ligne.", exampleTranslation: "Be wary of online scams." },
  { word: "trahir", pos: "verb", level: "B2", translation: "to betray", example: "Il a trahi la confiance de ses amis.", exampleTranslation: "He betrayed his friends’ trust." },
  { word: "remerciement", pos: "noun (m.)", level: "B1", translation: "thanks, expression of gratitude", example: "Un petit mot de remerciement suffit.", exampleTranslation: "A short thank-you note is enough." },
  { word: "faire la grasse matinée", pos: "expr.", level: "B2", translation: "to sleep in", example: "Le dimanche, j’adore faire la grasse matinée.", exampleTranslation: "On Sundays, I love to sleep in." },
  { word: "ras-le-bol", pos: "noun (m., expr.)", level: "B2", translation: "fed up, having had enough", example: "J’en ai ras-le-bol de ce bruit.", exampleTranslation: "I’ve had enough of this noise." },
  { word: "se planter", pos: "verb (refl.)", level: "B1", translation: "to mess up, to be wrong (informal)", example: "Je me suis planté dans le calcul.", exampleTranslation: "I messed up the math." },
  { word: "couvert", pos: "adj./noun", level: "A2", translation: "covered; cutlery, place setting", example: "Le ciel est couvert ce matin.", exampleTranslation: "The sky is overcast this morning." },
  { word: "régal", pos: "noun (m.)", level: "B2", translation: "a treat, a delight (often food)", example: "Ce dessert est un vrai régal.", exampleTranslation: "This dessert is a true delight." },
  { word: "chouchou", pos: "noun (m.)/adj.", level: "B1", translation: "favorite, teacher’s pet", example: "C’est le chouchou du prof.", exampleTranslation: "He’s the teacher’s pet." },
  { word: "miam", pos: "interj.", level: "A1", translation: "yum", example: "Miam, ça sent bon !", exampleTranslation: "Yum, it smells good!" },
  { word: "aïe", pos: "interj.", level: "A1", translation: "ouch", example: "Aïe, je me suis cogné le pied.", exampleTranslation: "Ouch, I stubbed my foot." },
  { word: "bof", pos: "interj.", level: "A2", translation: "meh, whatever", example: "— Tu as aimé le film ? — Bof.", exampleTranslation: "— Did you like the movie? — Meh." },
  { word: "chiffon", pos: "noun (m.)", level: "B1", translation: "rag, cloth", example: "Passe un chiffon sur la table.", exampleTranslation: "Wipe the table with a cloth." },
  { word: "se vexer", pos: "verb (refl.)", level: "B1", translation: "to take offense", example: "Ne te vexe pas, je plaisantais.", exampleTranslation: "Don’t take offense, I was joking." },
  { word: "agacement", pos: "noun (m.)", level: "B2", translation: "irritation, annoyance", example: "Un léger agacement se lisait sur son visage.", exampleTranslation: "A slight annoyance showed on his face." },
  { word: "bavard", pos: "adj.", level: "A2", translation: "talkative, chatty", example: "Ma grand-mère est très bavarde.", exampleTranslation: "My grandmother is very chatty." },
  { word: "feignant", pos: "adj./noun", level: "B2", translation: "lazy; lazy person (informal)", example: "Quel feignant, il dort encore !", exampleTranslation: "What a lazybones, he’s still sleeping!" },
  { word: "doux", pos: "adj.", level: "A1", translation: "soft, gentle, mild", example: "Cette laine est très douce.", exampleTranslation: "This wool is very soft." },
  { word: "renverser", pos: "verb", level: "B1", translation: "to knock over, to spill", example: "J’ai renversé mon verre d’eau.", exampleTranslation: "I knocked over my glass of water." },
  { word: "ronron", pos: "noun (m.)", level: "B2", translation: "purring; humdrum routine", example: "Le ronron du chat m’apaise.", exampleTranslation: "The cat’s purring soothes me." },
  { word: "se prélasser", pos: "verb (refl.)", level: "C1", translation: "to lounge, to laze around", example: "Je me prélasse au soleil tout l’après-midi.", exampleTranslation: "I lounge in the sun all afternoon." },
  { word: "écorcher", pos: "verb", level: "B2", translation: "to scrape; to mispronounce", example: "Il écorche tous les prénoms.", exampleTranslation: "He mispronounces every first name." },
  { word: "guérir", pos: "verb", level: "A2", translation: "to heal, to cure", example: "Ma blessure a mis du temps à guérir.", exampleTranslation: "My wound took a while to heal." },
  { word: "songe", pos: "noun (m.)", level: "C1", translation: "dream (literary)", example: "C’était comme un songe étrange.", exampleTranslation: "It was like a strange dream." },
  { word: "fidèle", pos: "adj.", level: "B1", translation: "loyal, faithful", example: "Mon chien est mon plus fidèle compagnon.", exampleTranslation: "My dog is my most loyal companion." },
  { word: "rugir", pos: "verb", level: "B2", translation: "to roar", example: "Le lion rugit dans la nuit.", exampleTranslation: "The lion roars in the night." },
  { word: "scintiller", pos: "verb", level: "B2", translation: "to sparkle, to twinkle", example: "Les étoiles scintillent au-dessus du lac.", exampleTranslation: "The stars sparkle above the lake." },
  { word: "boulet", pos: "noun (m.)", level: "B2", translation: "burden; (slang) clumsy person", example: "Quel boulet, j’ai oublié les clés !", exampleTranslation: "What an idiot, I forgot the keys!" },
  { word: "cinglé", pos: "adj.", level: "B2", translation: "crazy, nuts (informal)", example: "Tu es complètement cinglé !", exampleTranslation: "You’re completely nuts!" },
  { word: "louper le coche", pos: "expr.", level: "C1", translation: "to miss the boat", example: "Si tu hésites, tu vas louper le coche.", exampleTranslation: "If you hesitate, you’ll miss the boat." },
  { word: "futé", pos: "adj.", level: "B1", translation: "smart, clever", example: "Ce gamin est futé, il a tout compris.", exampleTranslation: "That kid is clever, he got it all." },
  { word: "se régaler", pos: "verb (refl.)", level: "B1", translation: "to enjoy oneself; to feast", example: "On s’est régalés avec ta tarte.", exampleTranslation: "We feasted on your pie." },
  { word: "fourrer", pos: "verb", level: "B2", translation: "to stuff; (refl.) to get oneself (somewhere)", example: "Où as-tu fourré mes lunettes ?", exampleTranslation: "Where did you stash my glasses?" },
  { word: "chichi", pos: "noun (m.)", level: "B2", translation: "fuss, pretense", example: "Pas de chichi, c’est juste un dîner entre amis.", exampleTranslation: "No fuss, it’s just dinner among friends." },
  { word: "polisson", pos: "adj./noun", level: "C1", translation: "naughty (playful)", example: "Petit polisson, va !", exampleTranslation: "You little rascal!" },
  { word: "se tromper", pos: "verb (refl.)", level: "A2", translation: "to be wrong, to make a mistake", example: "Je me suis trompé d’adresse.", exampleTranslation: "I got the wrong address." },
  { word: "rame", pos: "noun (f.)", level: "B1", translation: "oar; train (subway)", example: "Une rame arrive toutes les trois minutes.", exampleTranslation: "A train comes every three minutes." },
  { word: "rangée", pos: "noun (f.)", level: "A2", translation: "row", example: "Nous étions assis au premier rang.", exampleTranslation: "We were sitting in the front row." },
  { word: "épargner", pos: "verb", level: "B2", translation: "to save (money); to spare", example: "J’essaie d’épargner chaque mois.", exampleTranslation: "I try to save every month." },
  { word: "souvenir", pos: "noun (m.)/verb", level: "A2", translation: "memory; (refl.) to remember", example: "Je me souviens de mon premier voyage à Paris.", exampleTranslation: "I remember my first trip to Paris." },
  { word: "minute papillon", pos: "expr.", level: "C1", translation: "hold your horses, hold on a sec", example: "Minute papillon, je n’ai pas fini !", exampleTranslation: "Hold your horses, I’m not done!" },
  { word: "potache", pos: "adj./noun", level: "C1", translation: "schoolboy(ish), juvenile", example: "C’est une blague potache.", exampleTranslation: "It’s a schoolboy joke." },
  { word: "tantôt", pos: "adv.", level: "B2", translation: "soon; (in dialect) this afternoon", example: "À tantôt !", exampleTranslation: "See you later!" },
  { word: "rejoindre", pos: "verb", level: "B1", translation: "to join, to meet up with", example: "On te rejoint au café dans dix minutes.", exampleTranslation: "We’ll meet you at the café in ten minutes." },
  { word: "tatonner", pos: "verb", level: "C1", translation: "to fumble, to grope around", example: "J’ai tâtonné dans l’obscurité pour trouver l’interrupteur.", exampleTranslation: "I fumbled in the dark to find the switch." },
  { word: "miroiter", pos: "verb", level: "C1", translation: "to shimmer; to dangle (a hope)", example: "Le soleil miroitait sur l’eau.", exampleTranslation: "The sun shimmered on the water." },
  { word: "se moquer", pos: "verb (refl.)", level: "A2", translation: "to make fun of; to not care", example: "Je m’en moque complètement.", exampleTranslation: "I couldn’t care less." },
  { word: "fou rire", pos: "noun (m.)", level: "B1", translation: "fit of laughter", example: "On a eu un fou rire en classe.", exampleTranslation: "We had a fit of giggles in class." },
  { word: "navrer", pos: "verb", level: "B2", translation: "to sadden, to dismay", example: "Cette nouvelle me navre.", exampleTranslation: "This news saddens me." },
  { word: "abasourdi", pos: "adj.", level: "C1", translation: "stunned, dumbfounded", example: "Je suis resté abasourdi par sa réponse.", exampleTranslation: "I was left dumbfounded by his answer." },
  { word: "sieste", pos: "noun (f.)", level: "A2", translation: "nap, siesta", example: "Une petite sieste après le déjeuner, ça fait du bien.", exampleTranslation: "A short nap after lunch feels good." },
  { word: "marmonner", pos: "verb", level: "C1", translation: "to mumble", example: "Il marmonne toujours dans sa barbe.", exampleTranslation: "He always mumbles to himself." },
  { word: "péripéties", pos: "noun (f. pl.)", level: "C1", translation: "twists and turns of a story", example: "Le film raconte les péripéties d’un voyageur perdu.", exampleTranslation: "The film recounts the twists and turns of a lost traveler." },
  { word: "se faufiler", pos: "verb (refl.)", level: "B2", translation: "to slip through, to sneak in", example: "Il s’est faufilé jusqu’au premier rang.", exampleTranslation: "He slipped through to the front row." },
  { word: "ras", pos: "adj.", level: "B1", translation: "level with; short (hair)", example: "Le verre est plein à ras bord.", exampleTranslation: "The glass is filled to the brim." },
  { word: "balader", pos: "verb", level: "B1", translation: "to walk (sb/sth); (refl.) to wander", example: "Je promène le chien deux fois par jour.", exampleTranslation: "I walk the dog twice a day." },
  { word: "feuilleter", pos: "verb", level: "B2", translation: "to leaf through (a book)", example: "Je feuilletais une revue chez le dentiste.", exampleTranslation: "I was leafing through a magazine at the dentist’s." },
  { word: "boudoir", pos: "noun (m.)", level: "C1", translation: "small private sitting room; ladyfinger biscuit", example: "Elle l’invita dans son boudoir.", exampleTranslation: "She invited him into her boudoir." },
];
